// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OutlineManager","status":true,"description":"Changes the thickness of the font outline","parameters":{"Outline Width":"3"}},
{"name":"Lorg_DisableMovement","status":true,"description":"Simple Disable Movement","parameters":{"BlockSwitch":"19"}},
{"name":"HIME_DisabledChoiceConditions","status":true,"description":"v1.4 Allows you to disable individual choices in a set of options\r\nbased on custom conditions","parameters":{}}
];
