// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OutlineManager","status":true,"description":"","parameters":{"Outline Width":"3"}},
{"name":"DisableMovement","status":true,"description":"Plugin used to block all movement input via switch.","parameters":{"BlockSwitch":"21"}}
];
